DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`firstName` VARCHAR(50) NOT NULL,
	`lastName` VARCHAR(50) NOT NULL,
	`birthDate` DATE NOT NULL,
	`city` VARCHAR(50) NOT NULL,
	`country`	VARCHAR(10) NOT NULL,
	`avatar` VARCHAR(500) NOT NULL,
	`company`	VARCHAR(255) NOT NULL,
	`jobPosition` VARCHAR(255) NOT NULL,
	`mobile` VARCHAR(20) NOT NULL,
	`username` VARCHAR(50) NOT NULL,
	`email` VARCHAR(50) NOT NULL,
	`password` VARCHAR(50) NOT NULL,
	`role` VARCHAR(10) NOT NULL
);